spring.application.name=hrm

# 1. CẤU HÌNH KẾT NỐI DATABASE (POSTGRESQL)
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# 2. CẤU HÌNH HIBERNATE / JPA
# Tự động cập nhật bảng trong database khi Entity thay đổi (rất tiện khi code)
spring.jpa.hibernate.ddl-auto=update

# Hiển thị câu lệnh SQL trên console để dễ debug
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Định dạng dialect chuẩn cho PostgreSQL
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Chìa khóa bí mật (Phải đủ dài, trên 256 bit - Bạn có thể gõ bừa một chuỗi ký tự dài vào đây)
hrm.app.jwtSecret=${JWT_SECRET}

# Thời gian sống của token (Tính bằng mili-giây, ở đây là 1 ngày)
hrm.app.jwtExpirationMs=86400000